#!/bin/bash

rm ~/.tmux.conf
ln -s ~/programming/dotfiles/.tmux.conf ~/.tmux.conf

rm -rf ./.config/nvim/*
cp -rf ~/.config/nvim/* ./.config/nvim/

echo 'Update to github? (y/N)'
read ans

if [[ ${ans,,} == "y" ]]; then
    git add .
    git commit -m "update dotfiles"
    git push origin master
fi
