-- figure out how to do specific for java
-- print('filetype java ')
-- local attach = require("vm.lsp_attach")
-- require('java').setup()
-- require("lspconfig")['jdtls'].setup({
--     on_attach = attach.custom_attach,
--     capabilities = attach.default_capabilities,
-- })
-- vim.keymap.set('n', "<leader>to", "<cmd>JavaTestViewLastReport<cr>",
--     { noremap = true, desc = "[T]est [O]pen last report" })
