version: 2
log-file: /home/tqi_vsousa/.logs/efmls.log
log-level: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:
  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x -'
    # It's important to use lint-stding: true, see
    # https://github.com/mattn/efm-langserver/issues/59.
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

languages:
  sh:
    - <<: *sh-shellcheck
