#!/usr/bin/env sh

cd /tmp
wget https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-x86_64.tar.gz
tar xzvf nvim-linux-x86_64.tar.gz
sudo mv nvim-linux-x86_64 /usr/local/share/nvim-nightly
sudo ln -sf /usr/local/share/nvim-nightly/bin/nvim /usr/local/bin/vim

echo 'Done!'
